"""Cambios en db-historial

Revision ID: 445852db1009
Revises: b708a8c4ed55
Create Date: 2024-10-30 05:57:35.578149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445852db1009'
down_revision = 'b708a8c4ed55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.alter_column('persona_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.alter_column('persona_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
