"""Revision

Revision ID: b708a8c4ed55
Revises: 07da3a5c6751
Create Date: 2024-10-14 02:41:10.394050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b708a8c4ed55'
down_revision = '07da3a5c6751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.alter_column('persona_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.alter_column('persona_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
