"""Actualizacion de las tablas

Revision ID: cfe014d277d4
Revises: 445852db1009
Create Date: 2024-10-30 06:31:48.921895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe014d277d4'
down_revision = '445852db1009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesos')
    op.drop_table('persona_rol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_rol',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='persona_rol_persona_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name='persona_rol_rol_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='persona_rol_pkey')
    )
    op.create_table('accesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('es_valido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aula_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], name='accesos_aula_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='accesos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accesos_pkey')
    )
    # ### end Alembic commands ###
