from .ambiente.campus_controller import CampusController
from .ambiente.bloque_controller import BloqueController
from .ambiente.aula_controller import AulaController
from .personas.persona_controller import PersonaController
#from .personas.rol_controller import RolController
#from .personas.persona_rol_controller import PersonaRolController
#from .personas.usuario_controller import UsuarioController
#from .accesos.acceso_controller import AccesoController
#from .accesos.historial_controller import HistorialController
#from .permisos.permiso_controller import PermisoController
